### ISSUE TITLE
Is it possible to obtain the text representation generated fake examples? 

### ISSUE THREAD

**Issue by shebna12** [crux82/ganbert-pytorch#10]
Thank you for this Pytorch implementation! I'm quite new with GANs and curious if it's possible to text representation of the generated examples. Thought this would be possible since GANs when applied in computer vision tasks can generate images (i.e human faces). Hoping to hear from you soon :)

**Comment by crux82** [comment]
Unfortunately to the best of my knowledge, there is no method to derive a text from the generated vectors. I worked on this topic but it is quite challenging. 

GANs are effective in computer vision for generating images, but images are really different from texts. Images are made of pixels whose "values" are in a continuous space: in other words, you can slightly change the RED channel of a pixel and you just see it... less red. If you change just one byte in a sentence you can radically change its meaning.
(More technically, it is difficult to generate a text in the GANBERT training process as a sentence is not differentiable)

I would suggest considering different language models, such as GPT3 or BART.

Hope it helps

Bests

Danilo
