### ISSUE TITLE
Model errors when tried to change the dataset

### ISSUE THREAD

**Issue by mahmoudyusuf94** [crux82/ganbert-pytorch#7]
I am trying to run the notebook against a different dataset (QADI) and changed the data format to the same format specified in the example dataset

I just changed the get_qc_examples function to directly read the line and class from the tab-separated file:
```
def get_qc_examples(input_file):
  """Creates examples for the training and dev sets."""
  examples = []

  with open(input_file, 'r') as f:
      contents = f.read()
      file_as_list = contents.splitlines()
      for line in file_as_list[1:]:
          # split = line.split(" ")
          # question = ' '.join(split[1:])

          # text_a = question
          # inn_split = split[0].split(":")
          # label = inn_split[0] + "_" + inn_split[1]

          split = line.split("\t")
          question = split[1]

          text_a = question
          label = split[0]
          examples.append((text_a, label))
      f.close()

  return examples
```

I also came with some unlabeled data, set them to the same file format with the label set as `UNK_UNK`, changed the labels list to:

`label_list = ['UNK_UNK','Algeria', 'Bahrain', 'Egypt', 'Iraq', 'Jordan', 'Kuwait', 'Lebanon', 'Libya', 'Morocco', 'Oman', 'Palestine', 'Qatar', 'Saudi_Arabia', 'Sudan', 'Syria', 'Tunisia', 'United_Arab_Emirates', 'Yemen']
`

but I am getting an error at the end of the epoch (after training the whole epoch):
```
RuntimeError                              Traceback (most recent call last)
<ipython-input-11-3e8566791cab> in <module>()
    111         # so the loss evaluated for unlabeled data is ignored (masked)
    112         label2one_hot = torch.nn.functional.one_hot(b_labels, len(label_list))
--> 113         per_example_loss = -torch.sum(label2one_hot * log_probs, dim=-1)
    114         per_example_loss = torch.masked_select(per_example_loss, b_label_mask.to(device))
    115         labeled_example_count = per_example_loss.type(torch.float32).numel()

RuntimeError: The size of tensor a (63) must match the size of tensor b (64) at non-singleton dimension 0
```
Am I doing something wrong? can you help me tackle this issue?

**Comment by mahmoudyusuf94** [comment]
```
print(log_probs.shape)
--->torch.Size([64, 19])

print(label2one_hot.shape)
--->torch.Size([63, 19])
```

**Comment by crux82** [comment]
It was a bug. It was expected that the batch size would always be equal to the default value (i.e. 64) while some batches (especially the last of each epoch) might not contain that number of examples. 

I just committed a bug fix. 
Could you confirm that it solved your problem?

Bests 

Danilo
